[req]
distinguished_name	= "{{ req_distinguished_name }}"

[req_distinguished_name]
countryName = "{{ country_name }}" # Country Name (2 letter code)
countryName_min			= 2
countryName_max			= 2
localityName			= "{{ locality_name }}" # Locality Name (eg, city)
organizationName		= "{{ organization_name }}" # "Organization Name (eg, company)"
organizationalUnitName  = "{{ organization_unit_name }}" # "Organizational Unit Name (eg, section)"
commonName			    = "{{ common_name }}" # Common Name (eg, YOUR name)
commonName_max			= 64
emailAddress			= "{{ email_address }}" # Email Address
emailAddress_max		= 40
